// No `import 'dotenv/config'` here: Bun loads .env automatically at runtime.
// (prisma.config.ts keeps it, because the Prisma CLI evaluates that file itself.)
import postgres from '@prisma/orm-postgres/runtime';
// contract.d.ts and contract.json are generated by `bunx prisma contract emit`; re-run it after editing contract.prisma.
import type { Contract } from './contract.d';
import contractJson from './contract.json' with { type: 'json' };

const url = process.env['DATABASE_URL'];
if (!url) {
  throw new Error('DATABASE_URL is not set. Add it to apps/backend/.env (see .env.example).');
}

// Query with db.orm.public.<Model>, e.g. db.orm.public.User.select('id', 'username').all()
export const db = postgres<Contract>({
  contractJson,
  url,
});
